- hosts: localhost

  vars:
    region: ap-south-1
    active_mq_server_security_group_name: active-mq-sg
    instance_type: t2.nano
    base_image_name: ami-0889b8a448de4fc44
    number_of_instances_to_create: 1

  tasks:
    - name: Firewall Rules for Active MQ Server
      ec2_group:
        name: "{{ active_mq_server_security_group_name }}"
        description: Firewall Rules for Active MQ Server
        region: "{{ region }}"
        #outbound rules
        rules_egress:
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0
        #Inbound Rules
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

          - proto: tcp
            from_port: 8161
            to_port: 8161
            cidr_ip: 0.0.0.0/0

          - proto: tcp
            from_port: 61616
            to_port: 61616
            cidr_ip: 0.0.0.0/0

    - name: Start up an EC2 instance
      ec2:
        key_name: microservices-course-keypair
        group: "{{ active_mq_server_security_group_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ base_image_name }}"
        region: "{{ region }}"
        # wait for the server to come up
        wait: yes
        exact_count: "{{ number_of_instances_to_create }}"
        instance_tags:
          Name: Active MQ
        count_tag:
          Name: Active MQ
      register: ec2

    - name: Gather New IP Address of Ec2 Instances and add it to a inmemory group
      add_host:
        groups: new_ec2_instances
        hostname: "{{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"

      #If we don't wait for SSH port to respond
      #then in the apply patches step we are trying to
      #do ssh to the new ec2-instance which will fail.
    - name: Wait for SSH Port to respond
      wait_for:
        port: 22
        host: "{{ item.public_ip }}"
        state: started
      with_items: "{{ ec2.instances }}"

- hosts: new_ec2_instances, tag_Name_Active_MQ

  tasks:
    - name: Patch up the server
      yum: name=* state=latest
      become: yes

    - name: Install Jdk 1.8
      yum:
        name: java-1.8.0-openjdk-devel
        state: latest
      become: yes

    - name: Download Active MQ
      get_url:
        url: https://archive.apache.org/dist/activemq/5.14.3/apache-activemq-5.14.3-bin.tar.gz
        dest: /home/ec2-user/activemq.tar.gz

    - name: Unpack Active MQ
      unarchive:
        src: /home/ec2-user/activemq.tar.gz
        dest: /home/ec2-user/
        remote_src: yes

    - name: Build a link to the executable so it will become a service
      file:
        src: /home/ec2-user/apache-activemq-5.14.3/bin/activemq
        dest: /etc/init.d/activemq
        state: link
      become: yes

    - name: Start config server and make that enabled across reboots
      service:
        name: activemq
        state: started
        enabled: yes
      become: yes

    - name: Wait for Web port to respond
      wait_for:
        host: localhost
        port: 8161
        state: started

