# Provision an EC2 Instance

- hosts: localhost

  tasks:
    - name: Start up an EC2 instance
      ec2:
        key_name: microservices-course-keypair
        group: Jenkins-sg
        instance_type: t2.micro
        image: ami-0889b8a448de4fc44
        region: ap-south-1
        # wait for the server to come up
        wait: yes
        exact_count: 1
        instance_tags:
          Name: Jenkins Server Automated
        count_tag:
          Name: Jenkins Server Automated
      # Register started instances to ec2 variable
      register: ec2

    - name: Gather New IP Address of Ec2 Instances and add it to a inmemory group
      add_host:
        groups: new_ec2_instances
        hostname: "{{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"

      #If we don't wait for SSH port to respond
      #then in the apply patches step we are trying to
      #do ssh to the new ec2-instance which will fail.
    - name: Wait for SSH Port to respond
      wait_for:
        port: 22
        host: "{{ item.public_ip }}"
        state: started
      with_items: "{{ ec2.instances }}"


- hosts: new_ec2_instances

  tasks:
    - name: Apply Patches
      yum: name=* state=latest
      become: yes