# Provision an EC2 Instance

- hosts: localhost

  vars:
    region: ap-south-1
    jenkins_security_group_name: Jenkins-Server-sg
    instance_type: t3.large
    base_image_name: ami-0889b8a448de4fc44
    number_of_instances_to_create: 1

  tasks:
    - name: Firewall Rules
      ec2_group:
        name: "{{ jenkins_security_group_name }}"
        description: Firewall Rules for Jenkins Server
        region: "{{ region }}"
        #outbound rules
        rules_egress:
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0
        #Inbound Rules
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0



    - name: Start up an EC2 instance
      ec2:
        key_name: microservices-course-keypair
        group: "{{ jenkins_security_group_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ base_image_name }}"
        region: "{{ region }}"
        # wait for the server to come up
        wait: yes
        exact_count: "{{ number_of_instances_to_create }}"
        instance_tags:
          Name: Jenkins Server Automated
        count_tag:
          Name: Jenkins Server Automated
      # Register started instances to ec2 variable
      register: ec2

    - name: Gather New IP Address of Ec2 Instances and add it to a inmemory group
      add_host:
        groups: new_ec2_instances
        hostname: "{{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"

      #If we don't wait for SSH port to respond
      #then in the apply patches step we are trying to
      #do ssh to the new ec2-instance which will fail.
    - name: Wait for SSH Port to respond
      wait_for:
        port: 22
        host: "{{ item.public_ip }}"
        state: started
      with_items: "{{ ec2.instances }}"


- hosts: new_ec2_instances, tag_Name_Jenkins_Server_Automated

  tasks:
    - name: Ensure Apache is NOT installed on this server.
      yum:
        name: httpd
        state: absent
      become: yes

    - name: Patch up the server
      yum: name=* state=latest
      become: yes

    - name: Install Jdk 1.8
      yum:
        name: java-1.8.0-openjdk-devel
        state: latest
      become: yes

    - name: Add Jenkins Red Hat Repository
      yum_repository:
        name: Jenkins
        description: Jenkins Repo
        baseurl: http://pkg.jenkins.io/redhat-stable
      become: yes

    - name: Add Jenkins Public Key
      rpm_key:
        key: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key
      become: yes

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest
      become: yes

    - name: Start Jenkins and Enable acrooss Reboots
      service:
        name: jenkins
        state: started
        enabled: yes
      become: yes

    - name: Install Git
      yum:
        name: git
        state: latest
      become: yes
